# -*- coding: utf-8 -*-
"""Project4(Real Calculator2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iVmh-N_cc7ZvnoraskT-a0_zYW2FLxLJ
"""

def add(a,b):
  addition = a+b
  print('sum of',a,'and', b, 'is', addition)

def sub(a,b):
  substraction = a-b
  print('substraction of',a,'and', b, 'is', substraction)
def mul(a,b):
  multiplication = a*b
  print('multiplication of',a,'and', b, 'is', multiplication)

def div(a,b):
  division = a/b
  print('division of',a,'and', b, 'is', division)

def mod(a,b):
  modules = a%b
  print('modules of',a,'and', b, 'is', modules)

equ = input('Enter the equation: ')
count = 0
number1 = []
opc = 0
equ = list(equ)

for i in equ:
  count = count + 1
  if i == '+' or i == '-' or i == '/' or i == '*' or i == '%':
    operator = i
    opc = 1
    break;
  else:
    number1.append(i)
  
number2 = equ[count:]

number1 = int(''.join(number1))
number2 = int(''.join(number2))
operator = ' '.join(operator)

if operator == '+':
  add(number1,number2)

elif operator == '-':
   sub(number1,number2)

elif operator == '*':
  mul(number1,number2)

elif operator == '/':
  div(number1,number2)

elif operator == '%':
  mod(number1,number2)

else:
  print('Enter valid equation')