# -*- coding: utf-8 -*-
"""Project4(Real calculator)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o9h5LUG16GS-SRfdO25VB9ECe1ihYQHA
"""

def add(a,b):
  addition = a+b
  print('sum of',a,'and', b, 'is', addition)

def sub(a,b):
  substraction = a-b
  print('substraction of',a,'and', b, 'is', substraction)
def mul(a,b):
  multiplication = a*b
  print('multiplication of',a,'and', b, 'is', multiplication)

def div(a,b):
  division = a/b
  print('division of',a,'and', b, 'is', division)

def mod(a,b):
  modules = a%b
  print('modules of',a,'and', b, 'is', modules)

number1,operator,number2 = map(str,input('Enter your equation: ').split())
number1 = int(number1)
number2 = int(number2)

if operator == '+':
  add(number1,number2)

elif operator == '-':
   sub(number1,number2)

elif operator == '*':
  mul(number1,number2)

elif operator == '/':
  div(number1,number2)

elif operator == '%':
  mod(number1,number2)

else:
  print('Enter valid equation')

